# Generated by Django 5.0.1 on 2024-08-23 18:08

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
