# Generated by Django 5.0.1 on 2025-06-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariation',
            name='price',
            field=models.IntegerField(default=1, max_length=12),
        ),
    ]
