# Generated by Django 5.0.1 on 2025-06-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_sizevariation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizevariation',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
