# Generated by Django 5.0.1 on 2025-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_sizevariation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizevariation',
            name='kare',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
