# Generated by Django 5.0.1 on 2025-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_sizevariation_kare'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sizevariation',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
