# Generated by Django 5.0.1 on 2025-07-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_product_location_alter_sizevariation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitesShowFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
