# Generated by Django 5.0.1 on 2025-07-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_sitesshowfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesshowfooter',
            name='desktop_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesshowfooter',
            name='mobile_video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesshowfooter',
            name='tablet_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
