# Generated by Django 6.0.2 on 2026-03-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_sitesshowfooter_desktop_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=150),
        ),
    ]
