# Generated by Django 6.0.2 on 2026-04-14 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_bathroom_bedroom_condition_kitchen_parkingspace'),
        ('store', '0019_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bathroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.bathroom'),
        ),
        migrations.AddField(
            model_name='product',
            name='bedroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.bedroom'),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.condition'),
        ),
        migrations.AddField(
            model_name='product',
            name='kitchen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.kitchen'),
        ),
        migrations.AddField(
            model_name='product',
            name='parking_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.parkingspace'),
        ),
    ]
