# Generated by Django 6.0.2 on 2026-06-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_bathroom_product_bedroom_product_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(allow_unicode=True, max_length=150, unique=True),
        ),
    ]
