# Generated by Django 5.0.1 on 2025-02-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_video_url', models.URLField()),
                ('tablet_video_url', models.URLField()),
                ('desktop_video_url', models.URLField()),
                ('thumbnail_image', models.ImageField(upload_to='video_thumbnails/')),
            ],
        ),
    ]
