# Generated by Django 5.0.1 on 2025-02-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_image',
        ),
    ]
