# Generated by Django 5.0.13 on 2025-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon_image', models.ImageField(blank=True, null=True, upload_to='images/favicon')),
            ],
        ),
    ]
