# Generated by Django 5.0.1 on 2025-07-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
