# Generated by Django 6.0.2 on 2026-04-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom_name', models.CharField(default='No Bathroom', max_length=50, unique=True)),
                ('bathroom_slug', models.SlugField(max_length=100, unique=100)),
            ],
            options={
                'verbose_name': 'bathroom',
                'verbose_name_plural': 'bathrooms',
            },
        ),
        migrations.CreateModel(
            name='Bedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedroom_name', models.CharField(default='No Bedroom', max_length=50, unique=True)),
                ('bedroom_slug', models.SlugField(max_length=100, unique=100)),
            ],
            options={
                'verbose_name': 'bedroom',
                'verbose_name_plural': 'bedrooms',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(default='No Condition', max_length=50, unique=True)),
                ('condition_slug', models.SlugField(max_length=100, unique=100)),
            ],
            options={
                'verbose_name': 'condition',
                'verbose_name_plural': 'conditions',
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(default='No Kitchen', max_length=50, unique=True)),
                ('kitchen_slug', models.SlugField(max_length=100, unique=100)),
            ],
            options={
                'verbose_name': 'kitchen',
                'verbose_name_plural': 'kitchens',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_name', models.CharField(default='No Parking Space', max_length=50, unique=True)),
                ('parking_slug', models.SlugField(max_length=100, unique=100)),
            ],
            options={
                'verbose_name': 'parking space',
                'verbose_name_plural': 'parking spaces',
            },
        ),
    ]
