# Generated by Django 5.0.1 on 2025-06-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0005_remove_footer_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='phone_number_two',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
